
TILE_SIZE = 50
TILE_NUMBER_VERTICAL = 15

WIDTH = 1200
HEIGHT = TILE_NUMBER_VERTICAL * TILE_SIZE

# Settings:
DEADZONE_SENS = 0.15
MUSIC_VOLUME = 0.1
SFX_VOLUME = 0.2

# Fenêtre pygame
WINDOW_HEIGHT = TILE_NUMBER_VERTICAL * TILE_SIZE
WINDOW_WIDTH = 1200
FPS = 60
